version: "3.8"
services:
    mariadb:
        image: mariadb:10.5.4
        container_name: MariaDB
        ports:
            - 3306:3306
        volumes:
            - mariadb-data:/var/lib/mysql
    php:
        image: php:7.2-apache
        container_name: drupal8-php-7.2
        ports:
            - 80:80
        depends_on:
            - mariadb
        volumes:
            - drupal-data:/var/www/html/website

volumes:
    mariadb-data:
    drupal-data:
